language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -r requirements_dev.txt
script: pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: rdJvQX1KCkrKpCp+aWQRwu2ibqf77C2JsoFEfVciemzRchFPXFfSCuE6mf0jJbIsJaWucrZXhKedv8RUEYS1gdrsbT23CnjbyNkhZAD+901EJZdljqRuu859uNOnpuSw1EY2WXyHZdeCRXNNjihhVxY/GNTo6g2K5ymSXrzMB5W6Drx8lqCO2AkKVVUqxRPAKQ4ow3diGka9kCsbXDXKf2CPEX3rjFWNzGYaAcQVmoT6QhzLoRj5lOQe/BDqa1QwW0D9AG6RbBZCxQj9X+NciTLGsuBCZGMJ06lx/GmlnNX8ramRxvssGlt8tbFO7SB3YuEF3wI+N5wrKw2QuYe6fbxOB3WfgkM8stWigqteh3UeqPN/ihuGdnNtTr0Pw69tqmH1aahZvHFjxLx8pE4MskXHb1S+XVGC1ZrM4U95i8UDRCGszD3FxSHdWu6/J4o9H8T5yzYrX8thzvRR41wxSYxB5gtsyEjQGus+YQ7mzq2gV0G25nmaGqw3miYKq16TtUbrKVhXiQ0iHpgF58lSZkPC0EtqLh/SbkWUwZ71GnfYssgVYPD+FTFxZehX/NGp5hWDOqnNGQVHLoDRo9o/6oyNR3na5xhNcgwBm0ABJYTzSJzKA/bCZ+kb2CIEf0u5iRBYpc7m1csSJNRgX3dfrb0KzOnHSlb0Eb2FEqFil5I=
  on:
    branch: master
    repo: Joko013/graphene-objecttype-from-sqlalchemy-table
    python: 3.8
